### ISSUE TITLE
[kwin]: maximize apps

### ISSUE THREAD

**Issue by star-buck** [plasma-mobile/mobster#10]

**Comment by mgraesslin** [comment]
Please rebuild:
* kwayland
* kwin
* plasma-workspace

**Comment by mgraesslin** [comment]
kwinrc to switch to maximizing:

[Plugins]
org.kde.phone.multitaskingEnabled=false
kwin4_effect_eyeonscreenEnabled=false
kwin4_effect_windowapertureEnabled=false

[Windows]
Placement=Maximizing

**Comment by star-buck** [comment]
current apps open fullscreen, top panel is hidden

**Comment by mgraesslin** [comment]
> top panel is hidden

that's because plasma-workspace is not yet rebuild
