### ISSUE TITLE
[phonecalls] SIM card unlocking

### ISSUE THREAD

**Issue by sebasje** [plasma-mobile/mobster#102]
It seems there's no way to provide the SIM card PIN code, so my phone never connects to the cellular network, can't receive or make phonecalls, etc..

**Comment by notmart** [comment]
the homescreen itself is supposed to show a pin enter overlay when needed (in shell/views/desktop) if itdoesn't is to be fixed there

**Comment by mck182** [comment]
As a workaround you can enter it from konsole/ssh/adb shell using

qdbus org.ofono /ril_0 org.ofono.SimManager.EnterPin "pin" "you_pin_number_here"

**Comment by notmart** [comment]
should work after update of plasma-phone-components

**Comment by jriddell** [comment]
probably this is in previous build of plasma-phone-components at 22-Jun-2015 23:48UTC but I'll rebuild anyway...
