### ISSUE TITLE
[homescreen]: Ubuntu Phone .desktop files

### ISSUE THREAD

**Issue by aleixpol** [plasma-mobile/mobster#103]
It seems to be a common pattern among those applications that we'll need to be in a specific directory before running an application. The required directory is "Path" under "[Desktop Entry]".

**Comment by sebasje** [comment]
Hm, this will a change in KRun, I suppose? Also, I guess as Path is not a default FDO thing, we'll need to patch it for now?

**Comment by aleixpol** [comment]
Should be fixed:
https://github.com/plasma-mobile/plasma-phone-components/commit/b3e1fbea953bc15e6c4e984029c37e1c5726534a

**Comment by jriddell** [comment]
new plasma-phone-components is in on-demand repo
