### ISSUE TITLE
[packaging]  kinfocenter for energy kcm

### ISSUE THREAD

**Issue by sebasje** [plasma-mobile/mobster#104]
kinfocenter repo from kde git.
needed for the power consumption kcm
should be installed by default as well

The kinfocenter package is still at 5.2.2, 5.3 contains a module for energy consumption of individual processes.
We'd like to ship this on the phone.

**Comment by jriddell** [comment]
needs added to mobile ci which is currently down

**Comment by jriddell** [comment]
powerdevil bulit yesterday in mobile ci http://mobile.kci.pangea.pub/pool/main/p/powerdevil/

**Comment by jriddell** [comment]
wrong bug, still open

**Comment by jriddell** [comment]
I don't think I have privilages to add new jobs to jenkins

**Comment by star-buck** [comment]
@jriddell: you now should have admin rights, please try again if it works.

**Comment by jriddell** [comment]
logging out and in doesn't seem to give me any new powers

**Comment by star-buck** [comment]
@jriddell : what login you use, jriddell or "jr"?

**Comment by jriddell** [comment]
harald added kinfocentre jobs to mobile kci which are running now

**Comment by apachelogger** [comment]
built http://mobile.kci.pangea.pub:8080/job/vivid_unstable_kinfocenter_pub/

**Comment by apachelogger** [comment]
@jriddell  I also added it to mobster, so the next image should have it
