### ISSUE TITLE
[packaging] plasma-nm needs update

### ISSUE THREAD

**Issue by sebasje** [plasma-mobile/mobster#105]
Needs an update from either Plasma/5.3 or master branch (fix contained in both). Fixes missing and too small icons at the top, next to checkboxes.

**Comment by jriddell** [comment]
building in on-demand...

**Comment by jriddell** [comment]
didn't build, needs review

**Comment by jriddell** [comment]
should be in mobile CI http://mobile.kci.pangea.pub/pool/main/p/plasma-nm/
