### ISSUE TITLE
[kci phone]: build ci packages and store on kci repo

### ISSUE THREAD

**Issue by star-buck** [plasma-mobile/mobster#109]
package repository should be somewhere equivalent of this:
http://kci.pangea.pub/plasma-phone/debian/pool/main/

**Comment by star-buck** [comment]
new mobile packages repo home is up here:
http://mobile.kci.pangea.pub/pool/main/

@apachelogger :Lets try spinning a new IMG (112) before today's end.

**Comment by apachelogger** [comment]
@star-buck most mobile specific jobs are not built yet there is nothing to build an image from

**Comment by star-buck** [comment]
@apachelogger : How many mobile specific are left before we can spin an IMG again?

**Comment by apachelogger** [comment]
~20 still need jenkins jobs created and their initial build

**Comment by star-buck** [comment]
@apachelogger : how many packages do we have for mobile kci in total?
 Can't you reuse most of the on-demand-ones from dci?

**Comment by apachelogger** [comment]
sure. the on demand stuff is from friday though, so the image would be the same as the existing one as far as the phone is concerned
