### ISSUE TITLE
[IMG 118]: plasmashell is broken

### ISSUE THREAD

**Issue by star-buck** [plasma-mobile/mobster#114]

**Comment by notmart** [comment]
needs a new image, the new package is built

**Comment by jriddell** [comment]
building...

**Comment by star-buck** [comment]
@jriddell 
119 flashed, but Plasma seems to still crash?

**Comment by star-buck** [comment]
119 works after reboot, panel top and bottom sizes are tiny...

**Comment by star-buck** [comment]
seems only my phone, closing this.
