### ISSUE TITLE
[Packaging] Purpose packaging has been broken for some days

### ISSUE THREAD

**Issue by aleixpol** [plasma-mobile/mobster#129]
I wanted to see what's going on with the Purpose packaging, realized it's unable to find Qt5Qml:
http://mobile.kci.pangea.pub:8080/job/vivid_unstable_kaccounts-integration_bin/1/console

I'm unsure how to proceed from there.

**Comment by apachelogger** [comment]
@shadeslayer http://mobile.kci.pangea.pub:8080/job/vivid_unstable_kaccounts-integration_pub/2/console
double-pub makes literally no sense

**Comment by apachelogger** [comment]
@shadeslayer actually, sorry. someone blew up the repo

**Comment by apachelogger** [comment]
fixed qml thingy, probably fails because of too old telepathy now

**Comment by apachelogger** [comment]
http://mobile.kci.pangea.pub:8080/job/vivid_unstable_purpose_pub/1/
