### ISSUE TITLE
reboot thrift

### ISSUE THREAD

**Issue by jriddell** [plasma-mobile/mobster#134]
thrift got confused during a broken image build and I now can't log in, please reboot

**Comment by star-buck** [comment]
Which one is thrift?

**Comment by jriddell** [comment]
actually it's delta that needs rebooted, the arm server
212.47.235.137

**Comment by star-buck** [comment]
Will do.

Is delta still special now to the other three servers, then I rename it
properly, as it doesnt make sense to refer to it under a different name
than it was actually renamed to?

**Comment by star-buck** [comment]
up and running again
