### ISSUE TITLE
[packaging] bluez upgrade hangs during setup

### ISSUE THREAD

**Issue by sebasje** [plasma-mobile/mobster#135]
Installing the latest bluez packages (coming in through apt-get dist-upgrade on devel-proposed) makes dpkg hang forever when setting up the package after copying the new config files.

**Comment by sebasje** [comment]
Fixed, though now we found out that kernel support is lacking, so not much we can do about it.

Bluez5 packages and bluedevil seem to work now, though.

**Comment by aleixpol** [comment]
How can it work if the Kernel doesn't support it?

**Comment by jriddell** [comment]
ok removed bluedevil from the remaster script
