### ISSUE TITLE
[top-panel]: freezes when sliding up&down 2-3x times

### ISSUE THREAD

**Issue by star-buck** [plasma-mobile/mobster#16]

**Comment by notmart** [comment]
worked around in plasma-mobile-components repo master, needs to refresh that package

**Comment by star-buck** [comment]
@jriddell @apachelogger : please rebuilt package:
https://launchpad.net/~plasma-phone/+archive/ubuntu/ppa

**Comment by star-buck** [comment]
still freezes

**Comment by mgraesslin** [comment]
fixed in kwin with http://commits.kde.org/kwin/02cebe93a67bb6781e4642344a9a566ab94a1326

New kwin package needed.

**Comment by jriddell** [comment]
building now into on-demand repository...
