### ISSUE TITLE
[wifi]: says connected, but e.g. firefox or discover show no webcontent

### ISSUE THREAD

**Issue by star-buck** [plasma-mobile/mobster#256]

**Comment by bhush9** [comment]
This seems to be due to SSL errors, installing ntp package fixes it, I will install it on default image.

**Comment by bhush9** [comment]
This is quite strange issue.. half of time it works and half time it doesn't (even with ntp installed and correct time set).. investigating.

**Comment by bhush9** [comment]
This should be fixed for Nexus 5..

**Comment by bhush9** [comment]
This is now fixed? (there is Discover crash right now soon after starting but that's different issue)

**Comment by star-buck** [comment]
Well, firefox crashing really prevents from knowing its fixed, but i assume
so.

Other than that, can you (or anyone else) confirm networkmanager doesnt
accept wifi password upon first entering it in the applet, even if
correctly and pops up to ask a second time?
Seems like this for latest mobile as well as on desktop, e.g. pinebook.

**Comment by bhush9** [comment]
> Other than that, can you (or anyone else) confirm networkmanager doesnt accept wifi password upon first entering it in the applet, even if correctly and pops up to ask a second time?

I don't see this on current mobile image.. that said there was indeed a bug in plasma-nm which got fixed very recently... it might be that that bug fix is not released with latest plasma-nm version on pinebook.. but for mobile it works.
