### ISSUE TITLE
[activities]: allow to swipe to activities with left and right swipe (similar to android with multiple pages)

### ISSUE THREAD

**Issue by star-buck** [plasma-mobile/mobster#257]

**Comment by notmart** [comment]
a very experimental version is in master, when an image is built should be possible to see how behaves and eventually refine

**Comment by bhush9** [comment]
I will package it up for next image this week

**Comment by bhush9** [comment]
Latest image seems to have it included but it doesn't seem to be working (Swiping on homescreen have no effect and it instead scrolls app drawer)

**Comment by star-buck** [comment]
I suggest to ship 2 activities default activated, so its easier to explore
the possibilities of this right away.

**Comment by bhush9** [comment]
I just tested now, and it needs lot of precision to swipe and switch activity.. 75% of time it just scrolls app drawer.

**Comment by notmart** [comment]
in master should switch a bit more easily
