### ISSUE TITLE
flashing nexus5x no longer finishes

### ISSUE THREAD

**Issue by star-buck** [plasma-mobile/mobster#258]

**Comment by star-buck** [comment]
its showing "waiting for device" forever

**Comment by aleixpol** [comment]
I've had that before (with the nexus5), flashing with sudo helped, although it basically means that your system didn't recognize the nexus5x as a device you can temper with.

**Comment by bhush9** [comment]
is it at fastboot stage? (i.e very start of script?) or later when there are calls to adb wait-for-device?

**Comment by star-buck** [comment]
Later, device doesnt show up...

**Comment by bhush9** [comment]
Okay, so its case of adb wait-for-device thingie. Someone on telegram also had same issue, and he earlier provided me patch that worked for him.. I don't know why this never fails for me though :man_shrugging: 

https://github.com/plasma-phone-packaging/pm-flashtool/commit/e2ebd2aa3020440088e374a12d4fb5d4e9ce7f59

Can you try this?

**Comment by star-buck** [comment]
Please fix it so it works for all like it did before here.

**Comment by bhush9** [comment]
Yes, this commit above is supposed to fix it..

**Comment by notmart** [comment]
i just flashed the 5x with master from pm-flashtool, worked out of the box

**Comment by bhush9** [comment]
Yeah, device with plasma mobile on it already have no problem.. its just devices with android as @star-buck's new phone is..

**Comment by bhush9** [comment]
We can close this ticket I assume?
