### ISSUE TITLE
datetime: reads 1970 again

### ISSUE THREAD

**Issue by star-buck** [plasma-mobile/mobster#259]

**Comment by bhush9** [comment]
Are you connected to network? If so it would attempt to sync time from the ntp server..

**Comment by star-buck** [comment]
we had this working with a recent date before without ntp, so its a regression.

**Comment by bhush9** [comment]
This issue is fixed locally, marking it as needs shipping as image is left to publish.

**Comment by bhush9** [comment]
Newer image `20171214-165756` should fix at least 1970. However solution in this image is missing one last bit which makes it show exact correct time and date.. I will include it in next image.

**Comment by bhush9** [comment]
This is fixed properly in latest image. please test.

**Comment by bhush9** [comment]
https://github.com/plasma-phone-packaging/pm-flashtool/commit/7b40d3d6a0d9c3ddb88a811184f2f7ed5d6a634c you will also need this commit in flashtool... appearantly i forgot to push this fix earlier

**Comment by star-buck** [comment]
now it reads February 15th 2018 on todays date ;)
