### ISSUE TITLE
[buttons]: make volume up&down buttons work

### ISSUE THREAD

**Issue by star-buck** [plasma-mobile/mobster#26]

**Comment by mgraesslin** [comment]
The proper way in my opinion is the following:
* finish kglobalaccel port of Wayland (https://todo.kde.org/?controller=task&action=show&task_id=41 )
* ship kmix on the phone
* things start to work autmatically as kmix registers the global shortcuts

For the record: KWin already receives the volume key events. We can delegate them, but the only place I want them to be delegated to is kglobalaccel. Everything else means a phone-specific code path which later on needs to be removed again.

**Comment by star-buck** [comment]
redundant ticket
