### ISSUE TITLE
Low disk space right after flashing and starting some programs

### ISSUE THREAD

**Issue by star-buck** [plasma-mobile/mobster#268]

**Comment by bhush9** [comment]
I'll do two things about this issue,

- update flasher script to resize root partition after flashing is done
- include a resize-root-partition script in the pm-flashtool which will allow to resize partition to bigger size manually.

**Comment by bhush9** [comment]
https://github.com/plasma-phone-packaging/pm-flashtool/commit/4b04a7588aa7367fa24dad9626f8a34024d31810 Fixed

**Comment by star-buck** [comment]
so when flashing next image, it will be auto-resized?

**Comment by bhush9** [comment]
Yes, It will have 4GB of space (out of which approx 1.7GB-ish is used..
