### ISSUE TITLE
settings: kcms like "mobile theme" failed to load

### ISSUE THREAD

**Issue by star-buck** [plasma-mobile/mobster#271]

**Comment by bhush9** [comment]
It's fixed, just needs shipping iin image: https://github.com/plasma-phone-packaging/plasma-settings-packaging/commit/d4d88bb5a894555f213c9bfc6a8f3e2371cb6152

**Comment by star-buck** [comment]
also other kcms doesnt load, hope this fixes all of them to be normal loading

**Comment by bhush9** [comment]
Yes

**Comment by bhush9** [comment]
Fixed in `20171213-161601` image.

**Comment by star-buck** [comment]
works great again.
