### ISSUE TITLE
Plasma-Settings: does not invoke Home/Task/Close button, also blocks topmenubar from being dragged down

### ISSUE THREAD

**Issue by star-buck** [plasma-mobile/mobster#272]

**Comment by bhush9** [comment]
This is rather strange : I just investigated this and turns out we had fix for this same issue : https://cgit.kde.org/plasma-settings.git/commit/?id=3ad88ec14b4447f72d52d7df735e9e406a1f1df9

I will investigate further

**Comment by bhush9** [comment]
Fixed in recent git master, yet to land in new image which I am afraid I won't be able to today..

**Comment by bhush9** [comment]
Fixed in `20171219-163639`

**Comment by star-buck** [comment]
works
