### ISSUE TITLE
Set password for phablet to '1234' again 

### ISSUE THREAD

**Issue by star-buck** [plasma-mobile/mobster#273]

**Comment by star-buck** [comment]
1234 does not work

**Comment by star-buck** [comment]
any answer on this? i'm quite stuck on not knowing the password.

**Comment by bhush9** [comment]
Password is not set by default, you will need to set it with passwd command.. I do plan to fix flash script to set default password tomorrow

**Comment by star-buck** [comment]
Why is it suddenly no longer set?
Please set it to 1234 again.

**Comment by bhush9** [comment]
It was never set after we moved away from Ubuntu touch... There is limitation in lockscreen that if password is not set it will accept any password it can, which made entering 1234 in lock screen work, but in reality password was never set... It was always manual

**Comment by star-buck** [comment]
Okay, so lets set it again according to our documentation on the website to
1234 again.

On Dec 12, 2017 10:46 AM, "Bhushan Shah" <notifications@github.com> wrote:

It was never set after we moved away from Ubuntu touch... There is
limitation in lockscreen that if password is not set it will accept any
password it can, which made entering 1234 in lock screen work, but in
reality password was never set... It was always manual

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/blue-systems/pm-neon/issues/273#issuecomment-351149581>,
or mute the thread

**Comment by bhush9** [comment]
Fixed in https://github.com/plasma-phone-packaging/pm-flashtool/commit/e51fc3b790862cfc7a34cc502d389406d962c9b3
