### ISSUE TITLE
Question: How-to "adb shell" into current PM from remote konsole?

### ISSUE THREAD

**Issue by star-buck** [plasma-mobile/mobster#274]

**Comment by bhush9** [comment]
With halium 7 adb is not working so, instead a remote access is provided through USB networking,

When plasma mobile is connected through USB, it will expose USB tethering network (named usb0 or rndis0 or enp0usb*)

It will get IP address through DHCP automatically and then you will be able to ssh into it

```
ssh phablet@10.15.19.82
```

If IP address is not assigned automatically you need to apply IP address in range of 10.15.19.*

**Comment by star-buck** [comment]
thanks, but again whats the password to proceed?

**Comment by bhush9** [comment]
I just commented in other ticket.

**Comment by bhush9** [comment]
Marking as Ready for QA as password is set in #273
