### ISSUE TITLE
vplayer: doesnt playback any video file (tried mp4, mkv, webm), add: ubuntu-restricted-extras gstreamer1.0-plugins-bad gstreamer1.0-libav libavcodec-extra

### ISSUE THREAD

**Issue by star-buck** [plasma-mobile/mobster#277]
it displays stuck at 0:00/0:01, so i guess it's missinmg something for playback/decoding?

**Comment by bhush9** [comment]
Yes I had plan to work on QtMultimedia bits today, but unexpectedly there was issue which prevented image from booting. So couldn't finish it.. 

I'll work on it tomorrow

**Comment by star-buck** [comment]
here is whats needed:
"sudo apt install ubuntu-restricted-extras gstreamer1.0-plugins-bad gstreamer1.0-libav libavcodec-extra"

Works perfectly with HD video playback :)

**Comment by star-buck** [comment]
so just installing those packages will make everything work!

**Comment by bhush9** [comment]
That won't support all the video formats unfortunately, and also that video is software rendered so it's super laggy/and drops frames, I can install this package, but real solution is to get to gst-droid packaged.. which will also fix the camera

**Comment by bhush9** [comment]
Also, gst-droid avoids issue of inclusion and distribution of non-free ubuntu-restricted extra in image..

**Comment by star-buck** [comment]
I  am getting super smooth video playback, also support of most fileformats
I tried so far.

Please install as advised and spin a new img, also with audacioususoc
player.

On Dec 13, 2017 11:08 AM, "Bhushan Shah" <notifications@github.com> wrote:

Also, gst-droid avoids issue of inclusion and distribution of non-free
ubuntu-restricted extra in image..

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/blue-systems/pm-neon/issues/277#issuecomment-351490841>,
or mute the thread

**Comment by bhush9** [comment]
IMG `20171214-165756` fixes this.

I however still prefer to get gst-droid included to avoid the licensing issues with ubuntu-restricted-extras.
