### ISSUE TITLE
Appearance kcm: Choosing another theme like Breeze Dark doesnt fully apply the theme

### ISSUE THREAD

**Issue by star-buck** [plasma-mobile/mobster#278]

**Comment by notmart** [comment]
with a normal mouse wheel?
here one wheel step in the systemsettings sidebar scrolls by slightly less than the height of an entry, and seems to feel quite natural, should it be more?

**Comment by notmart** [comment]
I have a couple of questions:
* is there something specific that doesn't get applied? 
* is it from look&feel kcm or the plasma desktop theme kcm?

**Comment by star-buck** [comment]
Wrong ticket?

**Comment by star-buck** [comment]
While being on topic, this ticket is related to PM as in Plasma Mobile

**Comment by bhush9** [comment]
This seems to have been caused by out of date plasma-framework, fixed in `20171219-163639`

**Comment by star-buck** [comment]
works
