### ISSUE TITLE
[packages]: plasma-workspace needs rebuild

### ISSUE THREAD

**Issue by star-buck** [plasma-mobile/mobster#34]

**Comment by jriddell** [comment]
building on delta and will get uploaded to on-demand repository...

**Comment by star-buck** [comment]
please post link when finished where to find package to check, thx.

**Comment by jriddell** [comment]
plasma-workspace_5.3.1+git20150612.0027+14.04-0_armhf.deb is up
http://dci.pangea.pub/plasma-phone/debian/pool/main/p/plasma-workspace/
