### ISSUE TITLE
[packaging]: error installing plasma-maliit-framework, conflicting packages

### ISSUE THREAD

**Issue by star-buck** [plasma-mobile/mobster#39]
dpkg: error processing archive /var/cache/apt/archives/plasma-maliit-framework_0.0+git20150609-0ubuntu1~ubuntu15.04~ppa5_armhf.deb (--unpack):
 trying to overwrite '/usr/lib/libmaliit-plugins.so.0.99.0', which is also in package libmaliit-plugins0 0.99.0+git20130923+17fdf86-0ubuntu8

**Comment by star-buck** [comment]
to solve conflict, remove
libmaliit-plugins0 maliit-framework

**Comment by jriddell** [comment]
remove libmaliit-plugins0 maliit-framework  added to mobster script
plasma-maliit-framework building now in on-demand repo
