### ISSUE TITLE
[local builds] package deps for armhf packages broken

### ISSUE THREAD

**Issue by sebasje** [plasma-mobile/mobster#48]
Installing the build dependencies on the chroot fails for anything involving frameworks.

Reproduce: install the chroot, using the xbuilder script as described on https://github.com/plasma-mobile/docs/blob/master/Development_Setup.md , then try

apt-get build-dep -a armhf kwin

it'll fail due to dependency problems.

**Comment by star-buck** [comment]
should work now according to Aleix
