### ISSUE TITLE
[click]: run click based applications so they come up

### ISSUE THREAD

**Issue by star-buck** [plasma-mobile/mobster#56]

**Comment by sebasje** [comment]
Error log caught: 

wl_display@1: error 1: invalid arguments for android_wlegl_handle@38.add_fd
The Wayland connection experienced a fatal error (Invalid argument)
Wayland display got fatal error 22: Invalid argument
Additionally, errno was set to 22: Invalid argument
The display is now unusable, aborting.

**Comment by star-buck** [comment]
example:
Browser always works reliably, so apparently no application can be started if Browser fails to come up at some point

**Comment by star-buck** [comment]
probably related to being "click-apps", e.g. "Music"

**Comment by aleixpol** [comment]
Packaging the changes described in #21 (regarding making apparmor support wayland) makes them start properly.
