### ISSUE TITLE
[mobster]: Feedback and specific requests for IMG+1

### ISSUE THREAD

**Issue by star-buck** [plasma-mobile/mobster#58]
101: boots fine

**Comment by star-buck** [comment]
102: first try: did hang at google logo

**Comment by star-buck** [comment]
for IMG 103:
- rebuild simplelogin (should start maliit)
- rebuild plasma-maliit-plugins

**Comment by star-buck** [comment]
for IMG 104:
- rebuild simplelogin
- use updated mtp-server package from ods
The `mtp-server` command needs to be manually run.

    $ adb shell
    > $ export DISPLAY=:0
    > $ mtp-server

**Comment by star-buck** [comment]
this is ongoing, so ticket never closes :)

**Comment by jriddell** [comment]
new mtp-server is in

**Comment by star-buck** [comment]
for IMG 106:
* rebuild plasma-phone-components
- mtp-server from here is still not in: http://dci.pangea.pub/plasma-phone/debian/pool/main/m/mtp/

**Comment by star-buck** [comment]
for IMG 106:
* rebuild plasma-phone-components
- mtp-server from here is still not in: http://dci.pangea.pub/plasma-phone/debian/pool/main/m/mtp/

**Comment by jriddell** [comment]
Image 107 is up with new mtp-server (but not yet plasma-phone-components)

**Comment by star-buck** [comment]
for image 110:
- add koko package from ci packages so its installed default
