### ISSUE TITLE
[top panel]: pulling down sometimes crashes

### ISSUE THREAD

**Issue by star-buck** [plasma-mobile/mobster#59]

**Comment by mgraesslin** [comment]
I was able to catch an assert in libhybris. It might be related:
kwin_wayland: hwcomposer_window.cpp:274: void HWComposerNativeWindow::lockFrontBuffer(HWComposerNativeWindowBuffer**): Assertion `m_frontBuf->busy == 2' failed.
Application::crashHandler() called with signal 6; recent crashes: 1
QSocketNotifier: Invalid socket 9 and type 'Read', disabling...


Probably we need to spend some more time in trying to understand hwcomposer and get that up correctly. Currently I think it's still too much copy'n'paste from the libhybris demo.

**Comment by mgraesslin** [comment]
I haven't seen this crash in a while - is it still happening?

**Comment by star-buck** [comment]
seems fixed for now
