### ISSUE TITLE
Inhabilitate qpa_plugin.sh

### ISSUE THREAD

**Issue by aleixpol** [plasma-mobile/mobster#63]
$ apt-file search profile.d/qpa_plugin.sh
ubuntu-touch-session: /etc/profile.d/qpa_plugin.sh

Defines QT_QPA_PLATFORM=ubuntumirclient
This obviously won't work for us, should be QT_QPA_PLATFORM=wayland.
(Or ideally empty, but I think that it doesn't work nevertheless and tries to start X).

**Comment by jriddell** [comment]
etc/profile.d/qpa_plugin_wayland.sh added to plasma-phone-settings, building now
