### ISSUE TITLE
[dekko]: build into .deb package

### ISSUE THREAD

**Issue by star-buck** [plasma-mobile/mobster#65]
https://code.launchpad.net/~ubuntu-touch-coreapps-drivers/+recipe/dekko-daily

**Comment by star-buck** [comment]
code/recipe: https://code.launchpad.net/~ubuntu-touch-coreapps-drivers/+junk/dekko-packaging

**Comment by apachelogger** [comment]
old version from before it was converted to a click. either we enable using clicks or dekko needs substantial changes to the cmake code to get it back into proper system paths

the old version appears to do something semi-resaonable though, so here is that:
https://launchpad.net/~plasma-phone/+archive/ubuntu/ppa/+sourcepub/5142819/+listing-archive-extra

it has a slight modification over the actual build as the desktop file referenced a wrong exec path

**Comment by boudewijnrempt** [comment]
Okay... So that's how I killed my laptop on Monday morning?

**Comment by boudewijnrempt** [comment]
Ok -- so I'll check and see if I can make debs out of the latest version as well? Or do we form from the old version and go from there?

**Comment by star-buck** [comment]
latest version
