### ISSUE TITLE
[audio] enable audio

### ISSUE THREAD

**Issue by star-buck** [plasma-mobile/mobster#66]

**Comment by davidedmundson** [comment]
Done needs packaging.

**Comment by star-buck** [comment]
which package names? normal CI or ODS?

**Comment by star-buck** [comment]
test sound with this app:
https://uappexplorer.com/app/com.ubuntu.developer.robert-ancell.animal-farm

to install on phone, adb shell in and execute:

sudo apt-add-repository ppa:plasma-phone/ubuntu-apps
sudo apt-get update
sudo apt-get install animal-farm

**Comment by star-buck** [comment]
How can we test if volume is up and sound should be generally working?

**Comment by davidedmundson** [comment]
in adb shell run
 paplay /usr/share/sounds/ubuntu/ringtones/Ubuntu.ogg

**Comment by star-buck** [comment]
just tried this on the latest 109 IMG: still silence :(
@mck182 : any way we can make this working default?

**Comment by mck182** [comment]
I thought this is done by David's pulse audio config, which is what made it working here. I'm not sure if this was already packaged and present on the image however.

https://github.com/plasma-mobile/plasma-phone-settings/issues/1

**Comment by star-buck** [comment]
@apachelogger :
Add file below as /etc/pulse/default.pa (overwrite file shipped by pulseaudio) :
https://github.com/plasma-mobile/plasma-phone-settings/blob/master/etc/pulse/default.pa

**Comment by star-buck** [comment]
link is dead, so restore config file because we still need it?:
https://github.com/plasma-mobile/plasma-phone-settings/commit/b9f057cf19f80d027c650445b2a237beaa29a4ff

**Comment by star-buck** [comment]
for testing:
in adb shell run
paplay /usr/share/sounds/ubuntu/ringtones/Ubuntu.ogg 

sudo add-apt-repository ppa:plasma-phone/ubuntu-apps
sudo apt-get update
sudo apt-get install animal-farm

**Comment by star-buck** [comment]
to make animal-farm have sounds, this is required:
sudo apt-get remove qtubuntu-media

**Comment by jriddell** [comment]
mobster committed:
commit 8e885c9e649cbf23ae749f6556f1038b8642c8fe
Author: Jonathan Riddell <jr@jriddell.org>
Date:   Tue Jun 23 12:46:59 2015 +0200

    enable audio easier by removing qtubuntu-media and adding gstreamer0.10-fluendo-mp3
