### ISSUE TITLE
[mtp-server]: install new one on IMG to replace ubuntu-one

### ISSUE THREAD

**Issue by jriddell** [plasma-mobile/mobster#68]
mtp-server won't install on the image.  it's already there from the ubuntu image and the upgrade fails in the chroot remaster
"E0616 01:32:24.817618  1583 server.cpp:424] Error opening /dev/mtp_usb, aborting now..."

**Comment by jriddell** [comment]
try apt remove the old one first maybe

**Comment by star-buck** [comment]
installed with 107
