### ISSUE TITLE
[packaging]: patched qtdeclarative in CI

### ISSUE THREAD

**Issue by notmart** [plasma-mobile/mobster#72]
the qtdeclarative package needs the following patch to fix some touch event coordinates issues:
https://codereview.qt-project.org/#/c/114424/

**Comment by jriddell** [comment]
building now in PPA https://launchpad.net/~plasma-phone/+archive/ubuntu/ppa/+packages

**Comment by jriddell** [comment]
qemu failure, I knew there was a reason we don't use launchpad PPAs for building arm.  trying again in on-demand...

**Comment by star-buck** [comment]
Hey Jonathan,

with on-demand, you build them ending in our new repo?
http://mobile.kci.pangea.pub/pool/main/

As I understood, we now have all kci mobile packages there with the
possibility of selectively updating single ones on-demand...

Greetings, Clemens.

**Comment by jriddell** [comment]
well it compiled on delta ~/pbuilder/vivid_result/qtdeclarative-opensource-src_5.4.1-1ubuntu5kubuntu1.dsc but as on-demand is now gone it's not much use, I'll work out how to use mobile kci tomorrow

**Comment by star-buck** [comment]
@jriddell : ok, thanks!

**Comment by jriddell** [comment]
waiting for mobile ci to reappear

**Comment by star-buck** [comment]
@jriddell : mobile ci reappeared

**Comment by jriddell** [comment]
publishing on mobile ci needs ssh access to the publisher@ account which I don't think I have

**Comment by star-buck** [comment]
@jriddell : try again login to mobile jenkins with "jriddell", you should have adminstrative privileges now... if not, I probably need to restart server.

**Comment by jriddell** [comment]
got it in  http://mobile.kci.pangea.pub/pool/main/q/qtdeclarative-opensource-src/
