### ISSUE TITLE
[packaging]: remove apport

### ISSUE THREAD

**Issue by star-buck** [plasma-mobile/mobster#81]

**Comment by notmart** [comment]
together that, also whoopsie/libwhoopsie should probably be removed, but i see that there seems to be some weird dependencies, if i try to uninstall it, it tries to install half of gnome

**Comment by notmart** [comment]
apparently tough the library is harmless, the daemon is already away, so that should be fine

**Comment by jriddell** [comment]
fixed in mobster
commit f012aba603c7bcc64f4ce493979000793eaa250e
Author: Harald Sitter <sitter@kde.org>
Date:   Thu Jun 18 19:21:15 2015 -0700
