### ISSUE TITLE
[apps]: okular pdf reader

### ISSUE THREAD

**Issue by star-buck** [plasma-mobile/mobster#87]

**Comment by apachelogger** [comment]
@jriddell https://github.com/plasma-phone-packaging/okular/tree/kubuntu_unstable

install files need updating otherwise it should be good. perhaps you can twiddle the installs tomorrow morning

**Comment by star-buck** [comment]
@apachelogger : is okular package suppoed to land here: http://mobile.kci.pangea.pub/pool/main/ ?

**Comment by luebking** [comment]
Sidenote: you likely want https://github.com/xylosper/okular-backend-mupdf (originally written by Pino Toscano) because poppler performance sucks. Big time.

**Comment by apachelogger** [comment]
@star-buck yes

**Comment by star-buck** [comment]
@apachelogger @jriddell :
any update on packaging this?

**Comment by jriddell** [comment]
building now in on-demand..

**Comment by jriddell** [comment]
up at http://mobile.kci.pangea.pub/pool/main/o/okular/
harald should also add it to mobile kci (or teach me how to do so)
