### ISSUE TITLE
[home button]: should show the homescreen without button staying visibly active

### ISSUE THREAD

**Issue by star-buck** [plasma-mobile/mobster#95]

**Comment by notmart** [comment]
@mgraesslin: can the show desktop effect get automatically disabled when a new window arrives?

**Comment by mgraesslin** [comment]
That should be the case - I need to check with Thomas whether all Show Desktop related bug fixes made it into master branch, too.

**Comment by luebking** [comment]
Should have made unless my origin/master is wrong ;-)

Notice that new windows will *NOT* break the state *if* they
- "somehow belong to the desktop" (same client or transient for it) or
- are flagged keep above.

**Comment by mgraesslin** [comment]
I guess the problem is that ShellClient doesn't break the show desktop state yet

**Comment by luebking** [comment]
Indeed - Client breaks it in takeFocus() (rather than on plain showing to (a) keep focus stealing prevention in and (b) allow explicit breaking through window activation in the taskbar and such)

**Comment by mgraesslin** [comment]
Fixed with http://commits.kde.org/kwin/7e1e044948ba70bd6521dbc5b782d8bbbe67cd68

Please rebuild kwin

**Comment by jriddell** [comment]
building in on-demand...

**Comment by star-buck** [comment]
works, just needs visibly remove the blue :)
